<?php

namespace Database\Seeders;

use App\Models\Page;
use Illuminate\Database\Seeder;

class PageSeeder extends Seeder
{
    public function run(): void
    {
        $pages = [
            [
                'slug' => 'about-us',
                'title' => 'About Ecozeen Swap',
                'meta_title' => 'About Us — Ecozeen Swap',
                'meta_description' => 'Learn about Ecozeen Swap, the single-vendor crypto platform operated by Ecozeen Tech Ltd.',
                'content' => <<<'HTML'
<p>Ecozeen Swap is a cryptocurrency vendor platform operated by Ecozeen Tech Ltd, registered in Nigeria (RC 1835204) and the United Kingdom (16582062). Unlike peer-to-peer marketplaces, Ecozeen Swap is the sole counter-party for every trade on the platform &mdash; when you buy, sell, or swap crypto, you are trading directly with us.</p>
<h2>Our Mission</h2>
<p>We exist to make buying, selling, and swapping digital assets simple, transparent, and safe. No third-party ads, no waiting on strangers, no ambiguous escrow &mdash; just clear daily rates and fast settlement.</p>
<h2>How We Operate</h2>
<p>Every 24 hours, our team publishes a buy and sell rate for each supported crypto/fiat pair. These rates are visible on your dashboard with a live countdown, so you always know exactly what you're trading at and when the rate will refresh.</p>
<h2>Compliance &amp; Security</h2>
<p>We require basic identity verification (KYC) from every user, though verification does not block trading &mdash; unverified users can trade immediately at lower limits while their documents are reviewed. All financial operations are processed through secure, transaction-safe systems designed to protect your funds.</p>
HTML,
            ],
            [
                'slug' => 'contact-us',
                'title' => 'Contact Us',
                'meta_title' => 'Contact Us — Ecozeen Swap',
                'meta_description' => 'Get in touch with the Ecozeen Swap team for support, partnerships, or general enquiries.',
                'content' => <<<'HTML'
<p>We'd love to hear from you. Whether you have a question about your account, need help with a trade, or want to explore a partnership, fill out the form and our team will respond as soon as possible.</p>
HTML,
            ],
            [
                'slug' => 'privacy-policy',
                'title' => 'Privacy Policy',
                'meta_title' => 'Privacy Policy — Ecozeen Swap',
                'meta_description' => 'How Ecozeen Swap collects, uses, and protects your personal information.',
                'content' => <<<'HTML'
<p>Ecozeen Tech Ltd ("Ecozeen Swap", "we", "us") respects your privacy. This policy explains what information we collect, how we use it, and the choices you have.</p>
<h2>Information We Collect</h2>
<p>We collect information you provide directly (name, username, email, phone, address, KYC documents) and information generated by your use of the platform (transaction history, login activity, IP addresses).</p>
<h2>How We Use Your Information</h2>
<p>We use your information to provide and improve the platform, verify your identity, process transactions, detect and prevent fraud, and comply with legal obligations.</p>
<h2>Data Security</h2>
<p>Sensitive data, including KYC documents and payment details, is encrypted at rest. Access to this data is restricted to authorized personnel only.</p>
<h2>Your Rights</h2>
<p>You may request access to, correction of, or deletion of your personal data at any time by contacting our support team, subject to our legal and regulatory record-keeping obligations.</p>
HTML,
            ],
            [
                'slug' => 'terms-of-service',
                'title' => 'Terms of Service',
                'meta_title' => 'Terms of Service — Ecozeen Swap',
                'meta_description' => 'The terms and conditions governing your use of Ecozeen Swap.',
                'content' => <<<'HTML'
<p>These Terms of Service govern your access to and use of Ecozeen Swap, operated by Ecozeen Tech Ltd. By creating an account, you agree to these terms.</p>
<h2>Single-Vendor Trading</h2>
<p>Ecozeen Swap is the sole counter-party for all buy, sell, and swap transactions on the platform. There is no peer-to-peer marketplace, and users may not list or advertise trades to other users.</p>
<h2>Account Verification</h2>
<p>Basic identity verification (KYC) is required to fully unlock trading limits. We reserve the right to suspend accounts found to be in violation of these terms or engaged in fraudulent activity.</p>
<h2>Rates &amp; Settlement</h2>
<p>Buy and sell rates are set by Ecozeen Swap and refresh on a 24-hour cycle. Rates displayed at the time of your transaction are the rates that apply; once a trade is confirmed, it cannot be reversed.</p>
<h2>Prohibited Activity</h2>
<p>You may not use Ecozeen Swap for money laundering, terrorist financing, or any other unlawful purpose. We cooperate with law enforcement and regulatory authorities as required by law.</p>
<h2>Limitation of Liability</h2>
<p>Ecozeen Swap is provided "as is". To the maximum extent permitted by law, Ecozeen Tech Ltd is not liable for indirect or consequential damages arising from your use of the platform.</p>
HTML,
            ],
        ];

        foreach ($pages as $page) {
            Page::query()->updateOrCreate(['slug' => $page['slug']], array_merge($page, ['is_published' => true]));
        }
    }
}
